version: '3.8'

services:
  # 1. BACKEND
  backend:
    build: ./backend
    container_name: odev_backend
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - mongodb

  # 2. FRONTEND
  frontend:
    build: ./frontend
    container_name: odev_frontend
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - backend

  # 3. VERİTABANI
  mongodb:
    image: mongo:latest
    container_name: odev_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # 4. YENİ EKLENEN MCP SERVİSİ
  mcp_service:
    build: ./mcp
    container_name: odev_mcp
    ports:
      - "8001:8001"
    restart: always

volumes:
  mongo_data:
